language: bash

services:
- docker

env:
  global:
  - BASE_IMAGE_STABILITY_TAG=2.3.0
  - ALPINE_VER=3.8
  matrix:
  - NGINX_VER=1.17.1 TAGS=1.17,1,latest
  - NGINX_VER=1.16.0 TAGS=1.16
  - NGINX_VER=1.15.12 TAGS=1.15
  - NGINX_VER=1.14.2 TAGS=1.14
  - NGINX_VER=1.13.12 TAGS=1.13

script:
- make && make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
